require('./carousel');
require('./modal');
require('./accordeon');
require('./edgedrop');
require('./scroll-gallery-modal');
require('./tooltip');
require('./dropdown');
require('./map');
require('./tabs');
